x = int(input('Digite um numero inteiro para saber sua tabuada: '))
print('-----------')
print('{} x 0 = {:2}'.format(x, x*0))
print('{} x 1 = {:2}'.format(x, x*1))
print('{} x 2 = {:2}'.format(x, x*2))
print('{} x 3 = {:2}'.format(x, x*3))
print('{} x 4 = {:2}'.format(x, x*4))
print('{} x 5 = {:2}'.format(x, x*5))
print('{} x 6 = {:2}'.format(x, x*6))
print('{} x 7 = {:2}'.format(x, x*7))
print('{} x 8 = {:2}'.format(x, x*8))
print('{} x 9 = {:2}'.format(x, x*9))
print('{} x 10 = {:2}'.format(x, x*10))
print('-----------')
